#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 19 16:30:42 2020

@author: sandy
"""

def gcd (a, b):
    while (b):
        a %= b;
        a,b=b,a;
    return a;
print(gcd(28851538,1183019))
