#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 19 17:20:02 2020

@author: sandy
"""


def gcd (a, b):
    while (b):
        a %= b;
        a,b=b,a;
    return a;
def lcm(a,b):
    return (a*b)/gcd(a,b)
print(lcm(761457,614573))