#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 19 17:43:50 2020

@author: sandy
"""

def ltfibo(n):
    f=[]
    s=0
    f.append(0)
    f.append(1)
    for i in range(2,n+1):
        f.append(f[i-1]+f[i-2])
        s=s+f[i]
    #print(f[n]%10)
    print(s%10)
    return f[n]%10
ltfibo(3) 