#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 19 15:06:20 2020

@author: sandy
"""
from functools import lru_cache
@lru_cache(maxsize=1000) #default is 128
def fibo(n):
    if n<=1:
        return n
    return fibo(n-1)+fibo(n-2);
print(fibo(200))
for n in range(1,51):  #computing ratio b/w consecutive terms
    print(fibo(n+1)/fibo(n))  #gives golden ratio