#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 19 15:16:23 2020

@author: sandy
"""
def ltfibo(n):
    f=[]
    f.append(0)
    f.append(1)
    for i in range(2,n+1):
        f.append(f[i-1]+f[i-2])
    print(f[n]%10)
    return f[n]%10
ltfibo(331) 
#O(n)